SEED_RECIPES = [
    {
        "title": "Chicken Tomato Stir Fry",
        "ingredients": ["chicken", "tomato", "onion", "garlic", "cooking oil"],
        "ingredient_details": [
            {"name": "chicken", "quantity": 200, "unit": "g"},
            {"name": "tomato", "quantity": 2, "unit": "pieces"},
            {"name": "onion", "quantity": 1, "unit": "piece"},
            {"name": "garlic", "quantity": 2, "unit": "cloves"},
            {"name": "cooking oil", "quantity": 1, "unit": "tbsp"},
        ],
        "instructions": [
            "Cut the chicken into bite-sized pieces.",
            "Slice the tomato and onion.",
            "Heat cooking oil in a pan and cook the garlic until fragrant.",
            "Add chicken and stir fry until cooked through.",
            "Add tomato and onion, then cook until softened.",
        ],
        "cooking_time": 20,
        "difficulty": "easy",
        "servings": 2,
        "category": "main dish",
    },
    {
        "title": "Tomato Egg Stir Fry",
        "ingredients": ["tomato", "egg", "green onion", "cooking oil"],
        "ingredient_details": [
            {"name": "tomato", "quantity": 2, "unit": "pieces"},
            {"name": "egg", "quantity": 3, "unit": "pieces"},
            {"name": "green onion", "quantity": 1, "unit": "stalk"},
            {"name": "cooking oil", "quantity": 1, "unit": "tbsp"},
        ],
        "instructions": [
            "Beat the eggs in a bowl.",
            "Cut the tomatoes into wedges.",
            "Scramble the eggs in a hot pan, then remove them.",
            "Cook the tomatoes until juicy.",
            "Return the eggs to the pan and stir everything together.",
        ],
        "cooking_time": 15,
        "difficulty": "easy",
        "servings": 2,
        "category": "main dish",
    },
    {
        "title": "Chicken Omelette",
        "ingredients": ["chicken", "egg", "onion", "butter"],
        "ingredient_details": [
            {"name": "chicken", "quantity": 100, "unit": "g"},
            {"name": "egg", "quantity": 3, "unit": "pieces"},
            {"name": "onion", "quantity": 0.5, "unit": "piece"},
            {"name": "butter", "quantity": 1, "unit": "tbsp"},
        ],
        "instructions": [
            "Dice the cooked chicken and onion.",
            "Beat the eggs until smooth.",
            "Melt butter in a pan and cook the onion until soft.",
            "Add chicken, then pour in the eggs.",
            "Cook until the omelette is set.",
        ],
        "cooking_time": 15,
        "difficulty": "easy",
        "servings": 2,
        "category": "breakfast",
    },
    {
        "title": "Garlic Fried Rice",
        "ingredients": ["rice", "garlic", "egg", "soy sauce", "cooking oil"],
        "ingredient_details": [
            {"name": "rice", "quantity": 2, "unit": "cups"},
            {"name": "garlic", "quantity": 3, "unit": "cloves"},
            {"name": "egg", "quantity": 1, "unit": "piece"},
            {"name": "soy sauce", "quantity": 1, "unit": "tbsp"},
            {"name": "cooking oil", "quantity": 1, "unit": "tbsp"},
        ],
        "instructions": [
            "Mince the garlic.",
            "Heat oil in a pan and cook garlic until fragrant.",
            "Add rice and stir fry until hot.",
            "Push rice aside and scramble the egg.",
            "Season with soy sauce and mix well.",
        ],
        "cooking_time": 15,
        "difficulty": "easy",
        "servings": 2,
        "category": "rice dish",
    },
    {
        "title": "Vegetable Fried Rice",
        "ingredients": ["rice", "carrot", "peas", "corn", "egg", "soy sauce"],
        "ingredient_details": [
            {"name": "rice", "quantity": 2, "unit": "cups"},
            {"name": "carrot", "quantity": 1, "unit": "piece"},
            {"name": "peas", "quantity": 0.5, "unit": "cup"},
            {"name": "corn", "quantity": 0.5, "unit": "cup"},
            {"name": "egg", "quantity": 1, "unit": "piece"},
            {"name": "soy sauce", "quantity": 1, "unit": "tbsp"},
        ],
        "instructions": [
            "Dice the carrot.",
            "Cook carrot, peas, and corn in a pan until tender.",
            "Add rice and stir fry until hot.",
            "Scramble the egg into the rice.",
            "Season with soy sauce and serve.",
        ],
        "cooking_time": 20,
        "difficulty": "easy",
        "servings": 2,
        "category": "rice dish",
    },
    {
        "title": "Chicken Fried Rice",
        "ingredients": ["chicken", "rice", "egg", "garlic", "soy sauce"],
        "ingredient_details": [
            {"name": "chicken", "quantity": 150, "unit": "g"},
            {"name": "rice", "quantity": 2, "unit": "cups"},
            {"name": "egg", "quantity": 1, "unit": "piece"},
            {"name": "garlic", "quantity": 2, "unit": "cloves"},
            {"name": "soy sauce", "quantity": 1, "unit": "tbsp"},
        ],
        "instructions": [
            "Cut the chicken into small pieces.",
            "Cook the chicken and garlic in a hot pan.",
            "Add rice and stir fry until hot.",
            "Scramble the egg into the rice.",
            "Season with soy sauce and mix well.",
        ],
        "cooking_time": 20,
        "difficulty": "easy",
        "servings": 2,
        "category": "rice dish",
    },
    {
        "title": "Tomato Pasta",
        "ingredients": ["pasta", "tomato", "garlic", "olive oil", "basil"],
        "ingredient_details": [
            {"name": "pasta", "quantity": 180, "unit": "g"},
            {"name": "tomato", "quantity": 3, "unit": "pieces"},
            {"name": "garlic", "quantity": 2, "unit": "cloves"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp"},
            {"name": "basil", "quantity": None, "unit": None},
        ],
        "instructions": [
            "Boil the pasta until tender.",
            "Cook garlic in olive oil until fragrant.",
            "Add chopped tomatoes and simmer into a sauce.",
            "Toss pasta with the tomato sauce.",
            "Finish with basil if available.",
        ],
        "cooking_time": 25,
        "difficulty": "easy",
        "servings": 2,
        "category": "pasta",
    },
    {
        "title": "Egg Fried Rice",
        "ingredients": ["egg", "rice", "green onion", "soy sauce", "cooking oil"],
        "ingredient_details": [
            {"name": "egg", "quantity": 2, "unit": "pieces"},
            {"name": "rice", "quantity": 2, "unit": "cups"},
            {"name": "green onion", "quantity": 1, "unit": "stalk"},
            {"name": "soy sauce", "quantity": 1, "unit": "tbsp"},
            {"name": "cooking oil", "quantity": 1, "unit": "tbsp"},
        ],
        "instructions": [
            "Beat the eggs lightly.",
            "Heat oil in a pan and scramble the eggs.",
            "Add rice and stir fry until hot.",
            "Season with soy sauce.",
            "Top with sliced green onion.",
        ],
        "cooking_time": 15,
        "difficulty": "easy",
        "servings": 2,
        "category": "rice dish",
    },
]
